service: lessthantwo

app: lessthantwo
org: sbadams

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  cfnRole: arn:aws:iam::331757531648:role/cfnRole
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
      Resource:
        - Fn::GetAtt: [Rooms, Arn]
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"


functions:
  connectHandler:
    handler: handler.connectHandler
    events:
      - websocket:
          route: $connect

  disconnectHandler:
    handler: handler.disconnectHandler
    events:
      - websocket:
          route: $disconnect
          
  defaultHandler:
    handler: handler.defaultHandler
    events:
      - websocket:
          route: $default
          
  messageHandler:
    handler: handler.messageHandler
    events:
      - websocket:
          route: message


resources:
  Resources:
    Rooms:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rooms
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
